import { NextRequest, NextResponse } from 'next/server';

interface ReportRequest {
  title: string;
  format: 'html' | 'markdown';
}

export async function POST(request: NextRequest) {
  try {
    const body: ReportRequest = await request.json();
    const { title, format = 'html' } = body;

    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    let report = '';

    if (format === 'html') {
      report = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "SF Pro Display", Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #0f0f10;
            color: #e0e0e0;
        }
        h1 { color: #00FF41; border-bottom: 2px solid #00FF41; padding-bottom: 10px; }
        h2 { color: #00D4FF; margin-top: 30px; }
        h3 { color: #00FF41; }
        .critical { color: #FF0040; }
        .high { color: #FF6B00; }
        .medium { color: #FFA500; }
        .low { color: #00D4FF; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #333; }
        th { background: #1a1a1c; color: #00FF41; }
        .summary { background: #1a1a1c; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #333; color: #888; }
    </style>
</head>
<body>
    <h1>${title}</h1>
    <p><strong>Date:</strong> ${date}</p>
    <p><strong>Generated by:</strong> CyberStrike Dashboard</p>
    
    <div class="summary">
        <h2>Executive Summary</h2>
        <p>This security assessment report contains vulnerability scan results and security analysis findings.</p>
        <ul>
            <li><strong>Total Vulnerabilities:</strong> <span class="critical">12</span></li>
            <li><strong>Critical:</strong> <span class="critical">3</span></li>
            <li><strong>High:</strong> <span class="high">5</span></li>
            <li><strong>Medium:</strong> <span class="medium">3</span></li>
            <li><strong>Low:</strong> <span class="low">1</span></li>
        </ul>
    </div>
    
    <h2>Vulnerability Details</h2>
    <table>
        <thead>
            <tr>
                <th>Severity</th>
                <th>Type</th>
                <th>Target</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="critical">CRITICAL</td>
                <td>Remote Code Execution</td>
                <td>192.168.1.100</td>
                <td>RCE vulnerability in web application</td>
            </tr>
            <tr>
                <td class="high">HIGH</td>
                <td>SQL Injection</td>
                <td>example.com</td>
                <td>Potential SQL injection vulnerability</td>
            </tr>
            <tr>
                <td class="high">HIGH</td>
                <td>XSS</td>
                <td>example.com</td>
                <td>Cross-site scripting vulnerability found</td>
            </tr>
        </tbody>
    </table>
    
    <h2>Recommendations</h2>
    <ul>
        <li>Immediately patch critical vulnerabilities</li>
        <li>Implement proper input validation</li>
        <li>Update all software components</li>
        <li>Enable security headers and HTTPS</li>
        <li>Regular security audits recommended</li>
    </ul>
    
    <div class="footer">
        <p>This report was generated automatically by CyberStrike Dashboard.</p>
        <p>For questions or concerns, please contact the security team.</p>
    </div>
</body>
</html>`;
    } else {
      report = `# ${title}

**Date:** ${date}  
**Generated by:** CyberStrike Dashboard

## Executive Summary

This security assessment report contains vulnerability scan results and security analysis findings.

- **Total Vulnerabilities:** 12
- **Critical:** 3
- **High:** 5
- **Medium:** 3
- **Low:** 1

## Vulnerability Details

| Severity | Type | Target | Description |
|----------|------|--------|-------------|
| CRITICAL | Remote Code Execution | 192.168.1.100 | RCE vulnerability in web application |
| HIGH | SQL Injection | example.com | Potential SQL injection vulnerability |
| HIGH | XSS | example.com | Cross-site scripting vulnerability found |
| MEDIUM | Information Disclosure | example.com | Sensitive information exposed |
| LOW | Weak Cipher | example.com | Outdated TLS cipher suite |

## Recommendations

1. Immediately patch critical vulnerabilities
2. Implement proper input validation
3. Update all software components
4. Enable security headers and HTTPS
5. Regular security audits recommended

---

*This report was generated automatically by CyberStrike Dashboard.*
`;
    }

    return NextResponse.json({
      success: true,
      report,
      format,
    });
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Internal server error';
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}

